algo = input('Digite algo: ')
print('O tipo primitivo é: ', type(algo))
print('Só tem espaços? ', algo.isspace())
print('É um número? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanumérico? ', algo.isalnum())
print('Éstá em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
print('Você digigou algo que é {} para alfabético, {} para minúsculo e {} para número.'
      .format(algo.isalpha(), algo.islower(), algo.isnumeric()))
